INSERT INTO usuario (nombre) VALUES ('Miguel Angel');
INSERT INTO usuario (nombre) VALUES ('Juanjo');
INSERT INTO usuario (nombre) VALUES ('Pepe');
INSERT INTO usuario (nombre) VALUES ('Albertini');

INSERT INTO post(titulo, contenido, id_usuario) VALUES ('Lorem','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam sit amet tempor nunc. Curabitur adipiscing eros non aliquam fringilla. Proin semper ultrices semper. Vestibulum vel viverra orci. Morbi ut orci tristique, consectetur orci ut, varius mi. Aenean urna erat, luctus et magna vel, pretium fermentum quam. Cras id hendrerit quam, cursus lacinia tellus.',1);
INSERT INTO post(titulo, contenido, id_usuario) VALUES ('ipsum','Cras commodo molestie ante ut dapibus. Integer lacinia massa vel iaculis dapibus. Phasellus fermentum semper lacus sit amet dignissim. Proin nec pretium risus, sit amet luctus lectus. Etiam sagittis odio lacus, at semper elit pulvinar et. Integer suscipit at turpis eget egestas. Nulla id justo neque. Quisque et mauris ac odio cursus volutpat.',2);
INSERT INTO post(titulo, contenido, id_usuario) VALUES ('dolor','Integer justo purus, accumsan sed est vitae, pulvinar faucibus tortor. Pellentesque malesuada, elit eu tempus dignissim, erat ligula porta nisl, nec gravida tortor mi eu elit. Nullam pulvinar malesuada nunc at volutpat. Aenean eget luctus nibh, id consectetur lorem. Nulla ac iaculis diam. Fusce a arcu tincidunt, egestas mauris at, volutpat velit. Mauris auctor turpis aliquam lorem iaculis porta. Nunc sollicitudin augue vel sollicitudin lobortis.',3);
INSERT INTO post(titulo, contenido, id_usuario) VALUES ('sit','Curabitur ornare accumsan augue in posuere. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse sem velit, molestie euismod laoreet eget, imperdiet imperdiet diam. Fusce dictum eros sit amet augue fringilla, ut bibendum tellus ultrices. Nam ut libero tincidunt, sollicitudin est eu, rutrum augue. Fusce cursus lacus sit amet sem lacinia, nec euismod nibh elementum. Quisque cursus consectetur enim, a pretium urna semper eget. Vestibulum facilisis velit in dolor euismod, vehicula adipiscing felis accumsan. Nunc velit velit, sagittis ut gravida sed, ultrices fringilla ante. Maecenas lobortis vehicula libero, in laoreet enim ornare non. Duis et nibh et est venenatis viverra. Fusce dictum posuere scelerisque. Duis vel arcu cursus, rutrum turpis ut, pulvinar risus.',4);
INSERT INTO post(titulo, contenido, id_usuario) VALUES ('amet','Nullam non ipsum et nisi rhoncus eleifend in ut nisi. Maecenas mattis ultricies iaculis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin lorem eros, volutpat sed justo ullamcorper, vestibulum condimentum augue. Integer sodales congue ligula vitae feugiat. Nunc porttitor, ipsum sit amet venenatis blandit, urna risus tempus elit, id porta nibh lacus ut turpis. Vestibulum condimentum, diam et sodales mattis, sem leo vehicula mauris, vitae mollis diam erat imperdiet magna. Proin interdum ligula sollicitudin tincidunt placerat. Vivamus ut pellentesque odio. Sed ante sem, pretium in tellus eu, vestibulum dictum felis. Vestibulum sed erat ante. Morbi nulla velit, malesuada et gravida non, molestie vitae nisl. Phasellus placerat malesuada pulvinar.',1);
INSERT INTO post(titulo, contenido, id_usuario) VALUES ('consectetur','Ut at sapien eget dolor tincidunt lacinia eget sit amet nisi. Nunc nec enim vitae dui facilisis molestie in eu justo. Proin tempus urna diam, placerat adipiscing ligula semper volutpat. Donec ut cursus libero. In bibendum lorem sed venenatis ultricies. Vivamus ultrices justo vitae sapien ullamcorper, eu vestibulum diam dignissim. Quisque auctor iaculis nisi eget suscipit. Donec tempor commodo lacinia. Maecenas vel porta mauris, eget vestibulum nulla.',2);
INSERT INTO post(titulo, contenido, id_usuario) VALUES ('adipiscing','Duis ac purus sollicitudin leo tristique condimentum. Fusce commodo felis nec dui elementum ullamcorper. Phasellus imperdiet tortor ac ornare elementum. Ut et lorem id augue sollicitudin auctor. Suspendisse vitae massa pellentesque, congue neque sagittis, faucibus eros. Cras egestas commodo lacus nec vestibulum. Morbi pellentesque cursus augue, euismod hendrerit diam dapibus eget. Nam nisi risus, pulvinar vitae placerat a, lobortis vitae nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Donec viverra ornare augue, vitae faucibus enim tempus a. Curabitur dignissim urna rhoncus sem gravida ornare.',3);
INSERT INTO post(titulo, contenido, id_usuario) VALUES ('elit','Maecenas at leo id lorem tempor vestibulum ut id felis. Nunc vitae sagittis massa. Fusce at velit eu eros placerat ultricies et a magna. In aliquam massa malesuada odio molestie rhoncus. Sed convallis ultrices laoreet. Nam eu urna eget enim posuere aliquam ac sit amet lacus. Curabitur blandit magna tellus, ac tempor tellus pharetra dictum. Suspendisse ullamcorper, velit sit amet sagittis egestas, dui augue dapibus ante, ut pretium dui magna in massa. In et varius purus. Nullam in convallis est. Nullam ipsum ipsum, semper sit amet justo scelerisque, condimentum fermentum nulla. Suspendisse lacus nibh, malesuada eu elit a, gravida bibendum neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis at euismod tortor. Aenean quis sem pellentesque, feugiat arcu at, convallis mauris.',4);
INSERT INTO post(titulo, contenido, id_usuario) VALUES ('Aliquam','Praesent elementum adipiscing adipiscing. Curabitur consectetur id dolor at aliquet. In ac augue dolor. Cras rhoncus, nisi et feugiat accumsan, lectus elit dictum eros, vitae elementum nulla sapien at leo. Fusce eu volutpat sapien, sit amet viverra arcu. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras elit sapien, congue non condimentum eget, fermentum et nulla. Mauris vitae felis urna. Vestibulum non nulla aliquam, lobortis magna feugiat, posuere mi. Cras quis accumsan velit, non malesuada nulla. Duis tempor nunc ipsum, in malesuada sem fringilla vitae. Pellentesque at odio eleifend, condimentum dui in, malesuada orci. In eleifend, justo a vulputate mollis, risus nulla varius arcu, varius volutpat lorem massa a ante. Nulla laoreet elit placerat, iaculis ante a, adipiscing nisi. Ut vel leo id mauris laoreet sodales. Vivamus nec sodales erat.',1);